apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-forms
  namespace: feedback-forms
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: feedback-forms
  template:
    metadata:
      labels:
        app: feedback-forms
    spec:
      securityContext:
        fsGroup: 82  # Moved here at pod level
      volumes:
        - name: app-files
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: nginx-config
      initContainers:
        - name: app-files
          image: ghcr.io/feedback-forms/feedback-forms:dev
          command: ["/bin/sh", "-c", "cp -r /app/. /var/www/html/ && chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache && chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache"]
          volumeMounts:
            - name: app-files
              mountPath: /var/www/html
        - name: db-migrations
          image: ghcr.io/feedback-forms/feedback-forms:dev
          command:
            - /bin/sh
            - -c
            - |
              php artisan migrate --force
              php artisan session:table
              php artisan migrate --force
          env:
            - name: DB_CONNECTION
              value: "pgsql"
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: "feedback_forms"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
      containers:
        - name: php-fpm
          image: ghcr.io/feedback-forms/feedback-forms:dev
          securityContext:
            runAsUser: 82  # www-data user ID
            runAsGroup: 82 # www-data group ID
          volumeMounts:
            - name: app-files
              mountPath: /app
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: laravel-secret
                  key: app-key
            - name: DB_HOST
              value: postgres
            - name: DB_DATABASE
              value: "feedback_forms"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: MAIL_MAILER
              value: "smtp"
            - name: MAIL_HOST
              value: "mail.smtp2go.com"
            - name: MAIL_PORT
              value: "2525"
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: smtp-secret
                  key: username
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-secret
                  key: password
            - name: SESSION_DRIVER
              value: "database"
            - name: SESSION_LIFETIME
              value: "120"
            - name: DB_CONNECTION
              value: "pgsql"
            - name: DB_PORT
              value: "5432"
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: app-files
              mountPath: /app
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: feedback-forms
  namespace: feedback-forms
spec:
  selector:
    app: feedback-forms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80