apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-forms
  namespace: feedback-forms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feedback-forms
  template:
    metadata:
      labels:
        app: feedback-forms
    spec:
      volumes:
        - name: app-files
          emptyDir: {}
      initContainers:
        - name: app-files
          image: ghcr.io/feedback-forms/feedback-forms:dev
          command: ["/bin/sh", "-c", "cp -r /app/. /var/www/html/"]
          volumeMounts:
            - name: app-files
              mountPath: /var/www/html
      containers:
        - name: php-fpm
          image: ghcr.io/feedback-forms/feedback-forms:dev
          volumeMounts:
            - name: app-files
              mountPath: /app
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: laravel-secret
                  key: app-key
            - name: DB_HOST
              value: postgres
            - name: DB_DATABASE
              value: "feedback_forms"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: MAIL_MAILER
              value: "smtp"
            - name: MAIL_HOST
              value: "mail.smtp2go.com"
            - name: MAIL_PORT
              value: "2525"
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: smtp-secret
                  key: username
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-secret
                  key: password
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: app-files
              mountPath: /app
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: feedback-forms
  namespace: feedback-forms
spec:
  selector:
    app: feedback-forms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80