apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: feedback-forms
data:
  nginx.conf: |
    server {
        listen 80;
        root /app/public;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            fastcgi_pass feedback-forms:9000;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            include fastcgi_params;
        }
    }