name: CI/CD Pipeline

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy-test:
    needs: build
    if: ${{ !startsWith(github.ref, 'refs/tags/v') }}   # Deploy to test for all non-main branches
    uses: ./.github/workflows/deploy.yml
    with:
      environment: test
      image_tag: ${{ needs.build.outputs.image_tag }}
    secrets: inherit

  deploy-production:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')  # Deploy to production only from tags
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      image_tag: ${{ needs.build.outputs.image_tag }}
    secrets: inherit