name: CI/CD Pipeline

on:
  push:
    branches: [ main, feat/deployment ]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    needs: build
    # if: github.ref == 'refs/heads/master'  # Only deploy from master branch
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
    secrets: inherit