name: Deploy to Kubernetes

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: false
        default: 'production'
        type: string
      image_tag:
        description: 'Docker image tag to deploy'
        required: true
        type: string
    secrets:
      KUBE_CONFIG:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Create kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Update image tag
        run: |
          # Get the last tag (commit-sha) from the comma-separated list
          IMAGE_TAG=$(echo "${{ inputs.image_tag }}" | tr ',' '\n' | tail -n1 | tr -d ' ')

          # Update the image tags in deployment files
          sed -i "s|:dev|:${IMAGE_TAG#ghcr.io/feedback-forms/feedback-forms:}|g" deployments/app-deployment.yaml
          sed -i "s|:dev|:${IMAGE_TAG#ghcr.io/feedback-forms/feedback-forms:}|g" deployments/queue-deployment.yaml

      - name: Deploy PostgreSQL
        run: |
          kubectl apply -f deployments/postgres-deployment.yaml
          kubectl rollout status deployment/postgres -n feedback-forms
          # Wait for PostgreSQL to be fully ready
          kubectl wait --for=condition=ready pod -l app=postgres -n feedback-forms --timeout=120s

      - name: Deploy database setup
        run: |
          kubectl delete job db-setup -n feedback-forms --ignore-not-found
          kubectl apply -f deployments/db-setup-job.yaml
          kubectl wait --for=condition=complete job/db-setup -n feedback-forms --timeout=120s

      - name: Deploy application
        run: |
          kubectl apply -f deployments/

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/feedback-forms -n feedback-forms
          kubectl rollout status deployment/feedback-forms-queue -n feedback-forms

      - name: Verify application health
        run: |
          # Wait for ingress to be ready
          sleep 30
          curl -f https://feedback-forms.uts-x.com/health || exit 1
