name: Deploy to Kubernetes

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: false
        default: 'production'
        type: string
    secrets:
      KUBE_CONFIG:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Create kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployments/

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/feedback-forms -n feedback-forms
          kubectl rollout status deployment/feedback-forms-queue -n feedback-forms
          kubectl rollout status deployment/feedback-forms-nginx -n feedback-forms

      - name: Verify application health
        run: |
          # Wait for ingress to be ready
          sleep 30
          curl -f https://feedback-forms.uts-x.com/health || exit 1