name: Deploy to Kubernetes

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: false
        default: 'production'
        type: string
      image_tag:
        description: 'Docker image tag to deploy'
        required: true
        type: string
    secrets:
      KUBE_CONFIG:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Create kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Update image tag
        run: |
          IMAGE_TAG=$(echo "${{ inputs.image_tag }}" | tr ',' '\n' | tail -n1 | tr -d ' ')
          for file in deployments/*deployment.yaml deployments/db-setup-job.yaml; do
            sed -i "s|:dev|:${IMAGE_TAG#ghcr.io/feedback-forms/feedback-forms:}|g" "$file"
          done

      - name: Apply ConfigMaps and Secrets first
        run: |
          kubectl apply -f deployments/nginx-configmap.yaml
          # Wait for resources to be available
          sleep 5

      - name: Deploy PostgreSQL
        run: |
          kubectl apply -f deployments/postgres-deployment.yaml
          kubectl rollout status deployment/postgres -n feedback-forms --timeout=300s
          # Additional wait to ensure PostgreSQL is accepting connections
          kubectl wait --for=condition=ready pod -l app=postgres -n feedback-forms --timeout=300s

      - name: Deploy database setup
        run: |
          # Delete any existing job first
          kubectl delete job db-setup -n feedback-forms --ignore-not-found
          # Apply and wait for the new job
          kubectl apply -f deployments/db-setup-job.yaml
          kubectl wait --for=condition=complete job/db-setup -n feedback-forms --timeout=300s

      - name: Deploy application and queue
        run: |
          kubectl apply -f deployments/app-deployment.yaml
          kubectl apply -f deployments/queue-deployment.yaml
          kubectl apply -f deployments/ingress.yaml

      - name: Verify deployments
        run: |
          kubectl rollout status deployment/feedback-forms -n feedback-forms --timeout=300s
          kubectl rollout status deployment/feedback-forms-queue -n feedback-forms --timeout=300s

      - name: Health check
        run: |
          # Wait for ingress to be ready and DNS to propagate
          echo "Waiting for application to be ready..."
          for i in {1..20}; do
            if curl -f -k https://feedback-forms.uts-x.com/ -H 'Host: feedback-forms.uts-x.com' --retry 3 --retry-delay 10; then
              echo "Application is responding successfully"
              exit 0
            fi
            echo "Attempt $i/20 - Waiting 15 seconds before next attempt..."
            sleep 15
          done
          echo "Application failed to respond within timeout"
          kubectl get pods -n feedback-forms
          kubectl describe pods -n feedback-forms
          kubectl logs -n feedback-forms -l app=feedback-forms -c php-fpm --tail=100
          exit 1
